[package]
name = "protocash-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protocash-util = { path = "../protocash-util" }
tower = "0.4.13"
tower-abci = { git = "https://github.com/llGaetanll/tower-abci", branch = "main" }
cometbft-proto = "0.1.0-alpha.2"
cometbft = "=0.1.0-alpha.2"
bytes = "1.6.0"
tokio = "1.37.0"
prost = "0.12.4"
