[package]
name = "protocash-util"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-ff = "0.3.0"
ark-std = "0.3.0"
ark-snark = "0.3.0"
ark-bls12-381 = "0.3.0"
ark-ec = { version = "^0.3.0", default-features = false }
ark-ed-on-bls12-381 = { version = "0.3.0", features = ["r1cs"] }
ark-crypto-primitives = { version = "0.3.0", features = ["r1cs"] }
ark-relations = { version = "^0.3.0", default-features = false }
ark-r1cs-std = { version = "^0.3.0", default-features = false }
ark-serialize = { version = "^0.3.0", default-features = false }
arkworks-r1cs-gadgets = "0.5"
arkworks-native-gadgets = "0.5"
arkworks-utils = { version = "0.5", features = ["poseidon_bls381_x3_5"] }
rand = "0.8.5"
lazy_static = "1.4.0"
